###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 690
  packages: !include_dir_named packages
  customize: !include_dir_merge_named configuration/customize/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.1
    - type: homeassistant


#  whitelist_external_dirs:
#    - /config
#    - /config/tmp
#    - /config/backup/hass


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

###################################################
#                                                 #
#                     lovelace                    #
#                                                 #
###################################################
lovelace:
  mode: storage

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list configuration/automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list configuration/sensor/
zone: !include zones.yaml
notify: !include configuration/notify/notify.yaml
input_boolean: !include configuration/input_boolean.yaml
input_select: !include configuration/input_select.yaml
input_text: !include configuration/input_text.yaml
input_number: !include configuration/input_number.yaml

panel_iframe:
  dash:
    title: Node red Dash
    url: http://192.168.1.138:1880/endpoint/ui

####################################################
#                                                  #
#                    Telegram Bot                  #
#                                                  #
####################################################

#telegram_bot:
#  - platform: polling
#    api_key: !secret TelegramBotApiKey
#    allowed_chat_ids:
#      - !secret telegram_israel


####################################################
#                                                  #
#                      darksky                     #
#                                                  #
####################################################

## Weather Dark Sky
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api


# Example configuration.yaml entry
device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1


####################################################
#                                                  #
#             Check Internet speed                 #
#                                                  #
####################################################
# Example configuration.yaml entry
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload


####################################################
#                                                  #
#                    Switcher V2                   #
#                                                  #
####################################################

#switcher_kis:
#  phone_id: 0000
#  device_id: !secret switcher_device_id
#  device_password: 00000000

#switcher_aio:
#  phone_id: !secret switcher_phone_id
#  device_id: !secret switcher_device_id
#  device_password: !secret switcher_password
#  create_view: true
#  create_groups: true
#  schedules_scan_interval:
#    minutes: 5

####################################################
#                                                  #
#                    Air Condition                 #
#                                                  #
####################################################

remote:
  - platform: broadlink
    host: 192.168.1.121
    mac: !secret broadlink_mac_121

  - platform: broadlink
    host: 192.168.1.123
    mac: !secret broadlink_mac_121

  - platform: broadlink
    host: 192.168.1.125
    mac: !secret broadlink_mac_121

smartir:

climate:
  - platform: smartir
    name: Salon AC
    unique_id: salon_ac
    device_code: 8881
    controller_data: remote.salon_ir
    temperature_sensor: sensor.lumi_lumi_weather_a0144d03_temperature
    humidity_sensor: sensor.lumi_lumi_weather_a0144d03_humidity
    power_sensor: binary_sensor.lumi_lumi_sensor_magnet_76a74d04_on_off

#  - platform: smartir
#    name: Mahsan AC
#    unique_id: mahsan_ac
#    device_code: 972
#    controller_data: 192.168.1.123
#    temperature_sensor: sensor.tmprtvrh_slvn
#    humidity_sensor: sensor.tmprtvrh_slvn_2
#    power_sensor: binary_sensor.ac_salon_close_open_sensor

  - platform: smartir
    name: Horim AC
    unique_id: horim_ac
    device_code: 8882
    controller_data: remote.horim_ir
    temperature_sensor: sensor.lumi_lumi_weather_temperature
    humidity_sensor: sensor.lumi_lumi_weather_humidity
    power_sensor: binary_sensor.lumi_lumi_sensor_magnet_cae24d04_on_off

  - platform: smartir
    name: Kids AC
    unique_id: kids_ac
    device_code: 8882
    controller_data: remote.kids_ir
    temperature_sensor: sensor.lumi_lumi_sens_temperature
    humidity_sensor: sensor.lumi_lumi_sens_humidity
    power_sensor: binary_sensor.lumi_lumi_sensor_magnet_83e14d04_on_off


####################################################
#                                                  #
#                    Sonoff devices                #
#                                                  #
####################################################

sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_pass

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.1.100:8080/webcam/?action=snapshot
    mjpeg_url: http://192.168.1.100:8080/?action=stream

jewish_calendar:
  language: hebrew

cover:
  - platform: group
    entities:
      - cover.halon
      - cover.vitrina