
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

####################################################
#                                                  #
#                    Telegram Bot                  #
#                                                  #
####################################################

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_chat_id_israel

# Example configuration.yaml entry for the notifier
notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_id_israel 


####################################################
#                                                  #
#                      darksky                     #
#                                                  #
####################################################

## Weather Dark Sky
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api


# Example configuration.yaml entry
device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1


####################################################
#                                                  #
#                      xiaomi                      #
#                                                  #
####################################################
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_gateway_key
    - mac: !secret xiaomi_gateway_mac


####################################################
#                                                  #
#             Check Internet speed                 #
#                                                  #
####################################################
# Example configuration.yaml entry
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload


####################################################
#                                                  #
#                     Shabbat                      #
#                                                  #
####################################################
sensor:
  - platform: shabbat
    havdalah_calc: 42
    time_before_check: 10
    time_after_check: 10
    resources:
      - in
      - out
      - parasha
      - hebrew_date
      - is_shabbat  # state get True if is shabbat and False is shabbat end.