###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 650
  packages: !include_dir_named packages
  customize: !include_dir_merge_named configuration/customize/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.1
    - type: homeassistant


#  whitelist_external_dirs:
#    - /config
#    - /config/tmp
#    - /config/backup/hass


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

###################################################
#                                                 #
#                     lovelace                    #
#                                                 #
###################################################
lovelace:
  mode: storage

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
   cors_allowed_origins:
     - https://keitetran.github.io/BroadlinkIRTools/dist/#/

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list configuration/automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list configuration/sensor/
zone: !include zones.yaml
notify: !include configuration/notify/notify.yaml
input_boolean: !include configuration/input_boolean.yaml

panel_iframe:
  dash:
    title: Node red Dash
    url: http://192.168.1.138:1880/endpoint/ui

####################################################
#                                                  #
#                    Telegram Bot                  #
#                                                  #
####################################################

telegram_bot:
  - platform: polling
    api_key: !secret TelegramBotApiKey
    allowed_chat_ids:
      - !secret telegram_israel


####################################################
#                                                  #
#                      darksky                     #
#                                                  #
####################################################

## Weather Dark Sky
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api


# Example configuration.yaml entry
device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1


####################################################
#                                                  #
#             Check Internet speed                 #
#                                                  #
####################################################
# Example configuration.yaml entry
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload


####################################################
#                                                  #
#                    Switcher V2                   #
#                                                  #
####################################################

switcher_kis:
  phone_id: 0000
  device_id: !secret switcher_device_id
  device_password: 00000000

media_player:
  - platform: cast

input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - GalGalatz
      - Galatz
      - Radius 100FM
      - Echo 99FM
      - Kan 88FM
      - 103FM
      - Lev Hamedina 91FM
      - Reshet Gimel
      - Radio Darom
      - Kol Hayam Haadom 102FM
    icon: mdi:radio
  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Livingroom
      - Everywhere
    initial: Everywhere
    icon: mdi:speaker-wireless

smartir:

switch:
  - platform: broadlink
    host: 192.168.1.121
    mac: '34:ea:34:58:b6:e8'

  - platform: broadlink
    host: 192.168.1.123
    mac: 'b4:43:0d:cc:2e:af'

climate:
  - platform: smartir
    name: Salon AC
    unique_id: salon_ac
    device_code: 1560
    controller_data: 192.168.1.123
    temperature_sensor: sensor.tmprtvrh_slvn
    humidity_sensor: sensor.tmprtvrh_slvn_2
    power_sensor: binary_sensor.vytrynh