###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 650
  packages: !include_dir_named packages
  customize: !include_dir_merge_named configuration/customize/
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.1
    - type: homeassistant

#  whitelist_external_dirs:
#    - /config
#    - /config/tmp
#    - /config/backup/hass


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

###################################################
#                                                 #
#                     lovelace                    #
#                                                 #
###################################################
lovelace:
  mode: storage

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list configuration/automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list configuration/sensor/
zone: !include zones.yaml
notify: !include configuration/notify/notify.yaml


####################################################
#                                                  #
#                    Telegram Bot                  #
#                                                  #
####################################################

telegram_bot:
  - platform: polling
    api_key: !secret TelegramBotApiKey
    allowed_chat_ids:
      - !secret telegram_israel


####################################################
#                                                  #
#                      darksky                     #
#                                                  #
####################################################

## Weather Dark Sky
weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_api


# Example configuration.yaml entry
device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1


####################################################
#                                                  #
#                      xiaomi                      #
#                                                  #
####################################################
#xiaomi_aqara:
#  discovery_retry: 10
#  gateways:
#    - key: !secret xiaomi_gateway_key
#      host: 192.168.1.156


####################################################
#                                                  #
#             Check Internet speed                 #
#                                                  #
####################################################
# Example configuration.yaml entry
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload


####################################################
#                                                  #
#                    Switcher V2                   #
#                                                  #
####################################################

switcher_kis:
  phone_id: 0000
  device_id: !secret switcher_device_id
  device_password: 00000000

media_player:
  - platform: cast

input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - GalGalatz
      - Galatz
      - Radius 100FM
      - Echo 99FM
      - Kan 88FM
      - 103FM
      - Lev Hamedina 91FM
      - Reshet Gimel
      - Radio Darom
      - Kol Hayam Haadom 102FM
    icon: mdi:radio
  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Livingroom
      - Everywhere
    initial: Everywhere
    icon: mdi:speaker-wireless