## Home Assistant is Up and Running ##

- alias: 'Startup Notification'
  initial_state: 'on'  
  hide_entity: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.avi_telegram 
      data:
        title: 'System info'
        message: 'Home Assistant is Up and Running'